import React from 'react';

export const FETCH_COMMUNITY_POST = 'FETCH_COMMUNITY_POST';
export const FETCH_COMMUNITY_POST_REQUEST = 'FETCH_COMMUNITY_POST_REQUEST';
export const FETCH_COMMUNITY_POST_SUCCESS = 'FETCH_COMMUNITY_POST_SUCCESS';
export const FETCH_COMMUNITY_POST_FAILURE = 'FETCH_COMMUNITY_POST_FAILURE';
